#!/bin/bash

echo "🔧 Setting up User Sessions and Login Tracking in Supabase"
echo "=========================================================="
echo ""
echo "📋 Instructions:"
echo "1. Go to your Supabase Dashboard: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Go to SQL Editor"
echo "4. Copy and paste the contents of scripts/create-user-sessions-table-fixed.sql"
echo "5. Click 'Run' to execute the SQL"
echo ""
echo "✅ This will create:"
echo "   - user_sessions table"
echo "   - user_login_history table"
echo "   - log_user_login function"
echo "   - log_user_logout function"
echo "   - RLS policies"
echo ""
echo "🔗 SQL file location: scripts/create-user-sessions-table-fixed.sql"
echo ""
echo "After running the SQL, the 404 errors should stop and login tracking will work!" 