#!/bin/bash

echo "🧹 Clean Setup for User Sessions and Login Tracking"
echo "=================================================="
echo ""
echo "📋 Instructions:"
echo "1. Go to your Supabase Dashboard: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Go to SQL Editor"
echo "4. Copy and paste the contents of scripts/setup-user-sessions-clean.sql"
echo "5. Click 'Run' to execute the SQL"
echo ""
echo "✅ This will:"
echo "   - Drop existing tables and policies (if any)"
echo "   - Create fresh user_sessions table"
echo "   - Create fresh user_login_history table"
echo "   - Create log_user_login function"
echo "   - Create log_user_logout function"
echo "   - Set up RLS policies"
echo "   - Create indexes for performance"
echo ""
echo "🔗 SQL file location: scripts/setup-user-sessions-clean.sql"
echo ""
echo "After running this, the 404 errors should stop and login tracking will work!"
echo ""
echo "📝 Note: This script will delete any existing user session data."
echo "   If you have important session data, backup first!" 